image: gitpod/workspace-python-3.10

tasks:
  - name: test
    init: |
      pip install git+https://github.com/kedro-org/kedro.git@noklam/kedro-lsp 

# Kedro logging have weird interaction, the custom branch has disable it.

vscode:
    extensions:
        - noklam.noklam-vscode